language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - composer install --prefer-dist --dev
  - cd tests

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml